# Generated by Django 2.1.3 on 2018-11-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181128_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
